### ISSUE TITLE
Colons should probably be removed from filepath names 

### ISSUE THREAD

**Issue by EliasLeijon** [zenseact/zod#39]
I think dataset availability could be increased if camera_frame and lidar_frame filepaths were changed to not contain colons, so that they could work better with for example NTFS and exFAT file systems. Of course, renaming them manually is not that difficult for a user, but since some internal logic (such as time-parsing) is done using the file name I think it could be a worth while improvement to the dataset.

**Comment by wljungbergh** [comment]
Hi,

Thank you for your suggestion. Unfortunately, reuploading all data with new file names is currently not possible (and would cause some breaking changes...). One could consider adding functionality to the dev kit so that it can handle that logic depending on what OS you're running, however, it is not in scope for our current development plans. If you were to develop such logic we welcome a PR.

Please re-open this issue if you have any further questions/concerns.
